### ISSUE TITLE
Suggestion and Accusation dropdowns not populating correctly

### ISSUE THREAD

**Issue by JenTzori** [dfpreston/Clue-less-Colonel-Mustard-group-#10]
When trying to make a suggestion, no options are coming up in the pull down menus. This happens with 2 or more players, suggestions are fine with one player. Reproduced on deployed site and found the issue (for suggestions)
![image](https://user-images.githubusercontent.com/22458598/57575592-36396b00-7402-11e9-96f4-8e971ee7caa1.png)

This appears to be fixed by Kelly in this commit: https://github.com/dfpreston/Clue-less-Colonel-Mustard-group-/commit/36abb7a93a867ede2c3b4f262f7019d60e0a9bf2

Leaving this open until we can confirm on the deployed site

**Comment by megmello** [comment]
appears to be working  :)
