### ISSUE TITLE
Players unable enter an occupied room

### ISSUE THREAD

**Issue by JenTzori** [dfpreston/Clue-less-Colonel-Mustard-group-#11]
Game not allowing more than one player in a room
   Ex. choose Prof. Plum and Mrs. Peacock.  They should each be able to move into the Library from their hallways.  However, if one moves in, the Library will not be on the dropdown list for move options for the other.

Note from Jen - I believe this is fixed with PR #8 but leaving open until we can confirm on the deployed site

**Comment by megmello** [comment]
Resolved
