### ISSUE TITLE
Detective notebook not updating with cards seen in suggestion refutation

### ISSUE THREAD

**Issue by JenTzori** [dfpreston/Clue-less-Colonel-Mustard-group-#12]
Original bug: Can’t check off items in notebook at all -- even if item is seen

Note from Jen - notebook should be handled by the game, not user. The bug here is that the notebook isn't updating the checked off cards based on results from a suggestion

**Comment by JenTzori** [comment]
I believe this is fixed with PR #23

**Comment by megmello** [comment]
yup, detective notebook now updated with counter-evidence shown
