### ISSUE TITLE
Other players' tokens not displaying

### ISSUE THREAD

**Issue by JenTzori** [dfpreston/Clue-less-Colonel-Mustard-group-#14]
Only seeing (player’s) own character token on the game board.  All in-play characters should be shown. Also the weapons are only displaying when one player is playing.

**Comment by ktrages1** [comment]
I believe this should be fixed now

**Comment by megmello** [comment]
Can see other character tokens.  :)  Unfortunately, seem to be stacked on top of each other if in same room.

**Comment by megmello** [comment]
Also, not sure if "unassigned" character token is being pulled into Suggestion room as the icon did not appear for it.

**Comment by ktrages1** [comment]
Created new issue for the "unassigned" character part.

**Comment by ktrages1** [comment]
The multiple player tokens in a room displayed correctly for me now. Please confirm if you have a chance

**Comment by JenTzori** [comment]
During the runthrough today this looked right. Closing.
