### ISSUE TITLE
Character tokens not associated with player not displaying when suggested

### ISSUE THREAD

**Issue by ktrages1** [dfpreston/Clue-less-Colonel-Mustard-group-#29]

**Comment by ktrages1** [comment]
Added a Suspects class for database. Works on local, but needs to be tested with multiple players. 

To be tested:
- Token location update correctly
- If player makes a false accusation, location goes back to start space

**Comment by dfpreston** [comment]
I'm getting this on false Accusations, don't know if it's related or a different issue
![Screen Shot 2019-05-13 at 7 40 05 AM](https://user-images.githubusercontent.com/41966281/57628411-1d8e9980-7557-11e9-8bab-5bab1980d016.png)

**Comment by dfpreston** [comment]
It happens when you click to close the "You Lose" dialog box

**Comment by megmello** [comment]
Working now.
