### ISSUE TITLE
Players Assigned Duplicate Characters

### ISSUE THREAD

**Issue by megmello** [dfpreston/Clue-less-Colonel-Mustard-group-#36]
I ran with three machines: windows box and two iPhones.  Regardless of game creator, the selection of character on first iPhone was mirrored by auto-selection of same character on second phone.  If I followed by changing selection on second, the first auto-changed to match.  Windows machine maintained independence.

[changeset 4d98e5d]

**Comment by BernardVerna** [comment]
This bug should have been fixed with the character selection fix

**Comment by dfpreston** [comment]
Seems to work alright for me, I had three separate games running with the same characters
