### ISSUE TITLE
internal server error on false Accusation

### ISSUE THREAD

**Issue by dfpreston** [dfpreston/Clue-less-Colonel-Mustard-group-#38]
I did not think I change the loserUpdate method so I am unsure if this is related to that

![Screen Shot 2019-05-13 at 7 40 05 AM](https://user-images.githubusercontent.com/41966281/57628276-d7d1d100-7556-11e9-9a22-bb6b234b9a09.png)

**Comment by ktrages1** [comment]
Think this was an indexing issue, tried to use ".update()" on one player instance
