### ISSUE TITLE
Solution set cards not displaying correctly

### ISSUE THREAD

**Issue by JenTzori** [dfpreston/Clue-less-Colonel-Mustard-group-#9]
I can see the solution set correctly when I deploy locally, but remotely I'm seeing this:
![image](https://user-images.githubusercontent.com/22458598/57575559-aeebf780-7401-11e9-92df-7c0083e601a3.png)

Console looks like this:
![image](https://user-images.githubusercontent.com/22458598/57575565-bdd2aa00-7401-11e9-90a0-4a0432c2f56f.png)

@BernardVerna can you check that the images are where they're expected to be?

**Comment by JenTzori** [comment]
If we don't fix this before we record, let's keep the modal dialog but take out the images. The text should be sufficient.

**Comment by dfpreston** [comment]
They seem to be gone from static/images for some reason, the solution cards just never seem to end up there.
![Screen Shot 2019-05-11 at 10 01 39 PM](https://user-images.githubusercontent.com/41966281/57577621-67349280-7438-11e9-9682-e688682fe8d1.png)

**Comment by BernardVerna** [comment]
It's a problem on the host server....I'm fixing it now

**Comment by megmello** [comment]
Looks good for false accuser and winner cases.
